# Generated by Django 2.2.14 on 2020-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='blogpic',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='desc',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='header',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
